name: pictile
description: Fur Julia Niedzialek

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^0.3.9

  image_picker: ^0.6.3+4
  permission_handler: ^4.2.0+hotfix.3

  sqflite: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
