name: pictile
description: Fur Julia Niedzialek

version: 1.0.0+2

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^0.3.9
  image_picker: ^0.6.3+4

  sqflite: ^1.2.1
  provider: ^4.0.4
  path_provider: ^1.6.1
  permission_handler: ^4.2.0+hotfix.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab.ttf
